"""Writes every icon file Tack ships from the sources in this folder.

    python scripts/icon/build.py svg     # the SVG sources: app icon, tray, logo
    npx tauri icon crates/tack-app/icons/icon.svg -o crates/tack-app/icons
    (delete crates/tack-app/icons/android and .../ios)
    python scripts/icon/build.py png     # icon.ico, 32x32.png, tray PNGs, logo.png

Run `png` after `tauri icon`: tauri writes its own icon.ico and 32x32.png from
the master, and this replaces them with the hand-tuned small sizes.
Needs Python 3 with Pillow, Node 22+ and Chrome or Edge (render.mjs).
"""
import os, struct, subprocess, sys, tempfile
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import master, pixels

IC = os.path.join(REPO, "crates", "tack-app", "icons")
DESK = os.path.join(REPO, "ui", "dev", "desktop")
ASSETS = os.path.join(REPO, "docs", "assets")
PIXEL = (16, 20, 24, 32)

MASTER_NOTE = ("Tack: a framed felt board (brushed-aluminium frame, the board's green felt) "
               "seen a little from above, with a brass push-pin driven in diagonally; the board "
               "is 70% of the square, the pin 53% of its diagonal, the cap 31% of its width and "
               "over the top-right corner. Flat-topped cap with a bevelled rim and one specular "
               "point, waisted grip, flange, steel needle; one key light from the top left. "
               "Generated by scripts/icon (docs/design.md, \"Icon\"); 16-32 px are drawn by hand.")

def w(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text if text.endswith("\n") else text + "\n")

def grid(n):
    return pixels.load(os.path.join(HERE, "grids", f"{n}.txt"))

def svg_sources():
    m = master.build()
    w(os.path.join(IC, "icon.svg"), master.note(m, MASTER_NOTE))
    w(os.path.join(ASSETS, "logo.svg"), master.note(m, MASTER_NOTE))
    w(os.path.join(IC, "icon-48.svg"), master.note(master.build(48, 48),
      "Tack at 48 px: the master with the tile and its frame on whole pixels and no lower edge (scripts/icon)."))
    for n in PIXEL:
        rows = grid(n)
        w(os.path.join(IC, f"icon-{n}.svg"), pixels.to_svg(rows, "app",
          f"Tack at {n} px, drawn pixel by pixel (scripts/icon/grids/{n}.txt): the framed felt board, the brass pin's flat bevelled cap over its top-right corner, the waist, flange and needle."))
        for t in ("light", "dark"):
            w(os.path.join(IC, f"tray-{t}-{n}.svg"), pixels.to_svg(rows, t,
              f"Tack tray icon at {n} px for a {t} taskbar: icon-{n} with the {t} tuning (scripts/icon/pixels.py)."))
    for t in ("light", "dark"):
        w(os.path.join(IC, f"tray-{t}-64.svg"), master.note(master.build(64, 64, t),
          f"Tack tray icon at 64 px (scales above 200%) for a {t} taskbar (scripts/icon)."))
        w(os.path.join(DESK, f"tack-tray-{t}.svg"), pixels.to_svg(grid(32), t,
          f"Tack's tray icon ({t} taskbar) for the README scenes: a copy of crates/tack-app/icons/tray-{t}-32.svg."))
    print("svg sources written")

def render(jobs):
    """jobs: [(svg path, size, png path)] through headless Chrome."""
    args = [str(v) for j in jobs for v in j]
    subprocess.run(["node", os.path.join(HERE, "render.mjs"), *args], check=True)

def pngs():
    tmp = tempfile.mkdtemp(prefix="tack-ico-")
    big = {48: os.path.join(tmp, "48.png"), 256: os.path.join(tmp, "256.png")}
    render([(os.path.join(IC, "icon-48.svg"), 48, big[48]), (os.path.join(IC, "icon.svg"), 256, big[256]),
            (os.path.join(IC, "icon.svg"), 256, os.path.join(ASSETS, "logo.png")),
            (os.path.join(IC, "tray-light-64.svg"), 64, os.path.join(IC, "tray-light@2x.png")),
            (os.path.join(IC, "tray-dark-64.svg"), 64, os.path.join(IC, "tray-dark@2x.png"))])
    datas = []
    for n in PIXEL:
        rows = grid(n)
        p = os.path.join(tmp, f"{n}.png"); pixels.to_png(rows).save(p); datas.append((n, p))
        for t in ("light", "dark"):
            name = f"tray-{t}.png" if n == 32 else f"tray-{t}-{n}.png"
            pixels.to_png(rows, t).save(os.path.join(IC, name))
    pixels.to_png(grid(32)).save(os.path.join(IC, "32x32.png"))
    datas += [(48, big[48]), (256, big[256])]
    blobs = [open(p, "rb").read() for _, p in datas]
    head = struct.pack("<HHH", 0, 1, len(datas)); off = 6 + 16 * len(datas); ents = b""
    for (n, _), d in zip(datas, blobs):
        ents += struct.pack("<BBBBHHII", n % 256, n % 256, 0, 0, 1, 32, len(d), off); off += len(d)
    with open(os.path.join(IC, "icon.ico"), "wb") as fh:
        fh.write(head + ents + b"".join(blobs))
    print("icon.ico (16, 20, 24, 32, 48, 256), 32x32.png, tray PNGs, logo.png written")

if __name__ == "__main__":
    step = sys.argv[1] if len(sys.argv) > 1 else ""
    if step == "svg": svg_sources()
    elif step == "png": pngs()
    else: sys.exit(__doc__)
